### ISSUE TITLE
add.blank not defined

### ISSUE THREAD

**Issue by nicola883** [ErbB4/LaTex-bib#1]
To fix it, I have moved the definition of add.blank before the FUNCTION add.colon that calls it.

**Comment by ErbB4** [comment]
Hi @nicola883 , thank you for the comment. Could you please submit a pull request so I can merge it? Have a nice day.

**Comment by nicola883** [comment]
Hi.

Done.
Thank you for your work!

Nicola.

**Comment by ErbB4** [comment]
Thank you for your contribution!

Best,
Han
